[package]
name = "swiftness-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
solana-program = { git = "https://github.com/Okm165/solana.git", branch = "fix/deps"}
swiftness_air = { git = "https://github.com/iosis-tech/swiftness.git", rev = "b78639326e85c8d629c3cdeed4b9eeca29d717dd", default-features = false, features = ["recursive", "keccak_160_lsb", "stone5"] }
swiftness_stark = { git = "https://github.com/iosis-tech/swiftness.git", rev = "b78639326e85c8d629c3cdeed4b9eeca29d717dd", default-features = false, features = ["recursive", "keccak_160_lsb", "stone5"] }

[lib]
name = "swiftness"
crate-type = ["cdylib", "lib"]
