[package]
name = "allocator"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.210", features = ["derive"] }
solana-program = "2.0.9"

[lib]
name = "allocator"
crate-type = ["cdylib", "lib"]
